import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
          <main className='m-0 p-0 '>
            <div className='flex flex-col items-center justify-center min-h-screen py-2'>
              <h1 className='text-6xl font-bold'>
                Welcome to <a href="https://nextjs.org">Next.js!</a>
              </h1>
              <p className='mt-3 text-2xl'>
                Get started by editing{' '}
                </p>
                </div>
      </main>
    </>
  )
}
